name: MetaLearningDiversity
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.9.30
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - cryptography=3.4.8
  - cudatoolkit=10.2.89
  - dbus=1.13.18
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.2
  - intel-openmp=2021.3.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.2
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - scipy=1.7.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - urllib3=1.26.7
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - backports-entry-points-selectable==1.1.0
    - cfgv==3.3.1
    - colorama==0.4.4
    - cycler==0.10.0
    - distlib==0.3.3
    - filelock==3.3.1
    - identify==2.3.1
    - kiwisolver==1.3.2
    - nodeenv==1.6.0
    - platformdirs==2.4.0
    - pre-commit==2.15.0
    - pyhessian==0.1
    - pyyaml==6.0
    - toml==0.10.2
    - virtualenv==20.9.0
